### ISSUE TITLE
大佬，如何更换背景图片呀

### ISSUE THREAD

**Issue by 1104008306** [LOG1997/log-lottery#10]
大佬，我想把黑色的背景图片更换成自定义的图片，如何操作呀？

非常期待您的回复

**Comment by LOG1997** [comment]
> 大佬，我想把黑色的背景图片更换成自定义的图片，如何操作呀？
> 
> 非常期待您的回复

不能直接配置，可以在代码里面修改，修改这个组件就行https://github.com/LOG1997/log-lottery/blob/main/src/components/StarsBackground/index.vue

**Comment by 1104008306** [comment]
大佬，我尝试了一下，     // 直接设置背景图片样式
 document.body.style.backgroundImage = 'url("/src/1.jpg")';
图片也在src目录下，打开背景还是没有变化

**Comment by LOG1997** [comment]
> 大佬，我尝试了一下， // 直接设置背景图片样式 document.body.style.backgroundImage = 'url("/src/1.jpg")'; 图片也在src目录下，打开背景还是没有变化

在上面提到那个组件里，注释原有代码，直接修改为img

![image](https://github.com/LOG1997/log-lottery/assets/26322485/4aeb38c8-6fb3-48d4-a03b-76759000ebe4)

效果是这样

![image](https://github.com/LOG1997/log-lottery/assets/26322485/dab21941-1178-4bec-b339-b26856eb1ba9)

**Comment by 1104008306** [comment]
可以了，谢谢大佬。顺祝新年快乐， 万事如意！
