### ISSUE TITLE
怎么配置多轮抽奖呢，后续可以支持吗

### ISSUE THREAD

**Issue by mlike123** [LOG1997/log-lottery#11]
第一轮
  一等奖
  二等奖
  三等奖

第二轮
  一等奖
  二等奖
  三等奖

**Comment by LOG1997** [comment]
抽完过后，重置奖项设置就行了。如果要保存已设置的项目，可以将这个checkbox取消选中，这一项奖项就重置了
![image](https://github.com/LOG1997/log-lottery/assets/26322485/b5c33a62-1591-4070-b208-3420373cf578)
