### ISSUE TITLE
兄弟，有bug，还有需求，可以帮忙修改一下？

### ISSUE THREAD

**Issue by 92376** [LOG1997/log-lottery#2]
bug：
1. 导入 excel 模版后，点击抽奖，抽完一个，继续就卡住了
2. 重置数据后，抽奖列表数据还在

需求：
1. 已中奖需要从抽奖中移除
2. 一个奖项比如有10个，可否分几次抽
3. 音乐播放可以列表循环吗

**Comment by LOG1997** [comment]
你好，bug1已修复。初始化数据时字段类型用的是string类型，执行Array.push出错了。

**Comment by LOG1997** [comment]
@92376 bug2：重置数据只做了人员重置的功能。考虑到避免误操作，奖项重置需要手动重置，“已抽取”字段取消选择后该项就重置了
需求1：移除是指不在抽奖首页进行展示吗？
需求2：可以加个配置，配置每次抽取个数。
需求3：我又试了一下，播放最后一首过后是执行的列表循环又播放的第一首。

**Comment by 92376** [comment]
需求：
1.每个人只能中奖一次的意思
2.可以的
3.设置一首歌，不能自动循环播放，需要点击好像

**Comment by LOG1997** [comment]
> 需求：
> 1.每个人只能中奖一次的意思
> 2.可以的
> 3.设置一首歌，不能自动循环播放，需要点击好像

1.是按照奖项来配置的。只要在奖项列表里不点选“是否全员参与”，就是每人中奖一次的意思。
2 3.明天看看

**Comment by 92376** [comment]
1. 选择了，好像不生效

**Comment by 92376** [comment]
能不能再加个需求，我们公司的比如 5 等奖，有 10 个，但是分 5 类，能不能加个奖项配置列表，抽中一个人在这10个奖品里面随机一个，然后后面的人就只能随机9个，8等

**Comment by LOG1997** [comment]
> 1. 默认没有选择，好像不生效，还是会重复（可能是昨天类型问题导致的现在正常的）

抽奖名单重复这个没问题。
播放音乐当列表只有一首歌时无法循环的bug修复了。

**Comment by LOG1997** [comment]
> 能不能再加个需求，我们公司的比如 5 等奖，有 10 个，但是分 5 类，能不能加个奖项配置列表，抽中一个人在这10个奖品里面随机一个，然后后面的人就只能随机9个，8等，展示在抽中人卡片上

如此细粒度的配置没必要吧，增加复杂度。

**Comment by 92376** [comment]
谢谢

**Comment by 92376** [comment]
bug：160 个人，点击开始抽奖，抽取幸运儿，继续等按钮，有点卡顿，如果不等待，点击速度过快中奖数据会错乱

**Comment by LOG1997** [comment]
> bug：160 个人，点击开始抽奖，抽取幸运儿，继续等按钮，有点卡顿，如果不等待，点击速度过快中奖数据会错乱 优化：2024 高亮部分，颜色跳动，导致视觉效果不够明显

可以，晚上下班回去修复

**Comment by 92376** [comment]
快捷键操作：比如空格 进入抽奖，开始抽奖，继续，ESC取消🤣

**Comment by LOG1997** [comment]
> bug：160 个人，点击开始抽奖，抽取幸运儿，继续等按钮，有点卡顿，如果不等待，点击速度过快中奖数据会错乱 优化：2024 高亮部分，颜色跳动，导致视觉效果不够明显

1. 我用有几百个数据的列表都不卡顿啊。你说的卡顿应该是有等待时间吧？因为要等动画结束后才能进行相关操作。点击速度过快会导致数据错误得bug修复了。
2. 首页高亮图案部分减小了透明度，现在应该看起来对比度够了。

**Comment by 92376** [comment]
操作说明在默认主题下，看不清

**Comment by CrankAR** [comment]
麻烦请问每次抽取个数这个可以调整吗？

**Comment by LOG1997** [comment]
> 麻烦请问每次抽取个数这个可以调整吗？

暂时不行，后续空了加上
