### ISSUE TITLE
迫切需要配置背景颜色和背景图片的功能

### ISSUE THREAD

**Issue by wqzai** [LOG1997/log-lottery#30]

**Comment by LOG1997** [comment]
加了个背景可设置。在界面配置中可用。先在图片配置里上传一张你的图片，然后在界面配置选择背景

**Comment by wqzai** [comment]
十分感谢！


新诉求：
uid能不能和名字水平居中，然后uid、名字、部门三个垂直居中（上中下这样），音乐能不能新增抽奖中和中奖不同的音乐


Bug:
二等奖2个人的时候两个卡片没有居中显示






admin
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月21日(周六) 凌晨0:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LOG1997/log-lottery] 迫切需要配置背景颜色和背景图片的功能 (Issue #30)




 
加了个背景可设置。在界面配置中可用。先在图片配置里上传一张你的图片，然后在界面配置选择背景

**Comment by LOG1997** [comment]
有空的时候弄，我会选择合理的需求，不一定全部按照你的需求。
