### ISSUE TITLE
抽奖顺序可以进行调整吗？

### ISSUE THREAD

**Issue by CrankAR** [LOG1997/log-lottery#4]
另外还发现个bug，点击抽奖按钮过快的话会导致抽奖失败、抽奖人数最少，无法重新抽奖

**Comment by CrankAR** [comment]
另外还发现个bug，点击抽奖按钮过快的话会导致抽奖失败、抽奖人数不对，无法重新抽

**Comment by CrankAR** [comment]
![QQ截图20240119150149](https://github.com/LOG1997/log-lottery/assets/31739531/6054ea75-7f57-41f0-8a79-2596d2be1eff)
就像这样，我想先抽三等奖最后抽一等奖，但是在配置里调整的抽奖顺序，三等奖在最上面，很怪

**Comment by LOG1997** [comment]
> ![QQ截图20240119150149](https://private-user-images.githubusercontent.com/31739531/297980693-6054ea75-7f57-41f0-8a79-2596d2be1eff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTc2ODQsIm5iZiI6MTcwNTY1NzM4NCwicGF0aCI6Ii8zMTczOTUzMS8yOTc5ODA2OTMtNjA1NGVhNzUtN2Y1Ny00MWYwLThhNzktMjU5NmQyYmUxZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5NDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzM2ZkMmJhY2NkNWZhMWZmYmFiODEyNzI4OWUzMzQ3YjQyN2ZjM2EyNGU2YTI0MDU4NTcxNWNhZTA1ZTNjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoWr3EterHPemQd1YJ0gFOBoTMZCdnN4VXkXG_QNc8c) 就像这样，我想先抽三等奖最后抽一等奖，但是在配置里调整的抽奖顺序，三等奖在最上面，很怪

配置里面调整了顺序，页面上也跟着调整顺序了啊

**Comment by LOG1997** [comment]
> 另外还发现个bug，点击抽奖按钮过快的话会导致抽奖失败、抽奖人数最少，无法重新抽奖

点击按钮速度过快导致数据计算错误得bug修复了
