### ISSUE TITLE
在IDEA中dev运行总是卡死

### ISSUE THREAD

**Issue by xxsq** [LOG1997/log-lottery#8]
在IDEA中dev运行总是卡死
卡死后,哪怕重启也没法再打开了
比如第一次用localhost打开,卡死,后面就再无法用localhost打开
然后换本地IP 能打开,过一会又会卡死,就再也无法打开了
好像和更换主题有一定关系,在演示 https://24years.top/log-lottery/home 里面更换了主题之后,好像也会卡死

**Comment by LOG1997** [comment]
请问下您的系统和版本，使用的是什么浏览器和浏览器的版本呢。

> 在IDEA中dev运行总是卡死 卡死后,哪怕重启也没法再打开了 比如第一次用localhost打开,卡死,后面就再无法用localhost打开 然后换本地IP 能打开,过一会又会卡死,就再也无法打开了 好像和更换主题有一定关系,在演示 https://24years.top/log-lottery/home 里面更换了主题之后,好像也会卡死

**Comment by xxsq** [comment]
> 请问下您的系统和版本，使用的是什么浏览器和浏览器的版本呢。
> 
> > 在IDEA中dev运行总是卡死 卡死后,哪怕重启也没法再打开了 比如第一次用localhost打开,卡死,后面就再无法用localhost打开 然后换本地IP 能打开,过一会又会卡死,就再也无法打开了 好像和更换主题有一定关系,在演示 https://24years.top/log-lottery/home 里面更换了主题之后,好像也会卡死

WIN 10 企业版22H2 19045.3803
浏览器:
Microsoft Edge 版本 120.0.2210.144 (正式版本) (64 位)
Chrome 版本 121.0.6167.86（正式版本） （64 位）
这两个都试过,都有这个状况

**Comment by xxsq** [comment]
NODE 是18.18.0  不知道和这个版本是否有关?
对前端不是很熟,还望作者指点,非常感谢

**Comment by xxsq** [comment]
用浏览器的隐私模式,打开演示站点:https://24years.top/log-lottery/home
开始正常,上传人员名单后卡死,关掉浏览器再可以重新打开
如果不用隐私模式,就无法再打开了
怀疑和卡死和缓存有一定关系

**Comment by LOG1997** [comment]
> 用浏览器的隐私模式,打开演示站点:https://24years.top/log-lottery/home 开始正常,上传人员名单后卡死,关掉浏览器再可以重新打开 如果不用隐私模式,就无法再打开了 怀疑和卡死和缓存有一定关系

很遗憾😂并没有复现相关情况，在虚拟机装了个win10，只用了CPU两个进程，实际测试并没有问题，内存占用也只有不到300MB，并没有卡死的情况。

**Comment by LOG1997** [comment]
> 用浏览器的隐私模式,打开演示站点:https://24years.top/log-lottery/home 开始正常,上传人员名单后卡死,关掉浏览器再可以重新打开 如果不用隐私模式,就无法再打开了 怀疑和卡死和缓存有一定关系

![image](https://github.com/LOG1997/log-lottery/assets/26322485/5f9e85c9-65f4-410c-8081-8d5f49498970)

**Comment by LOG1997** [comment]
https://log1997.github.io/log-lottery/
进这个地址试一下呢，这个是较新的代码。如果还有报错可以进界面配置，点重置所有数据。

**Comment by xxsq** [comment]
> https://log1997.github.io/log-lottery/ 进这个地址试一下呢，这个是较新的代码。如果还有报错可以进界面配置，点重置所有数据。

好像发现问题所在了,之前导入的人员比较少,5个左右,就会出现卡死的情况
然后我换了一个90人的名单,就正常运行了

**Comment by LOG1997** [comment]
> > https://log1997.github.io/log-lottery/ 进这个地址试一下呢，这个是较新的代码。如果还有报错可以进界面配置，点重置所有数据。
> 
> 好像发现问题所在了,之前导入的人员比较少,5个左右,就会出现卡死的情况 然后我换了一个90人的名单,就正常运行了

ok，bug解决了我先把代码推上去，我再测试下明天布到https://log1997.github.io/log-lottery/这个地址

**Comment by xxsq** [comment]
> > > https://log1997.github.io/log-lottery/ 进这个地址试一下呢，这个是较新的代码。如果还有报错可以进界面配置，点重置所有数据。
> > 
> > 
> > 好像发现问题所在了,之前导入的人员比较少,5个左右,就会出现卡死的情况 然后我换了一个90人的名单,就正常运行了
> 
> ok，bug解决了我先把代码推上去，我再测试下明天布到[https://log1997.github.io/log-lottery/这个地址](https://log1997.github.io/log-lottery/%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80)

感谢,辛苦了
